[package]
description = "Derive macro for `documented`"
edition = "2021"
license = "MIT"
name = "documented-derive"
repository = "https://github.com/cyqsimon/documented"
version = "0.1.0"

[lib]
proc_macro = true

[dependencies]
quote = "1.0.28"
syn = "2.0.18"
